# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCenterClusterUsage',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='hypervisorhost',
            name='hypervisorusage_name',
        ),
        migrations.AlterField(
            model_name='vcentercluster',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='HypervisorUsage',
        ),
        migrations.AddField(
            model_name='vcentercluster',
            name='VCenterClusterUsage_name',
            field=models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.PROTECT, to='ServerAdmin.VCenterClusterUsage'),
            preserve_default=False,
        ),
    ]
