# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0002_auto_20160121_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='capacity',
        ),
        migrations.AddField(
            model_name='nfs_storage',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='[TB]'),
            preserve_default=False,
        ),
    ]
