# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0003_auto_20160121_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalserver',
            name='usage',
        ),
        migrations.AlterField(
            model_name='hypervisorhost',
            name='hdd_capacity_GB',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
        migrations.AlterField(
            model_name='hypervisorhost',
            name='memory_capacity_GB',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
        migrations.AlterField(
            model_name='nfs_storage',
            name='capacity',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='cpu',
            field=models.PositiveIntegerField(help_text='[core]'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='memory_GB',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
        migrations.AlterField(
            model_name='vmattachedvirtualhdd',
            name='capacity_GB',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
    ]
