# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0004_auto_20160121_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='serial',
            field=models.CharField(default='None', max_length=128, unique=False),
            preserve_default=False,
        ),
    ]
