# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0005_rack_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='serial',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
