# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0006_auto_20160121_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypervisorhost',
            name='cpu_core_num',
        ),
        migrations.RemoveField(
            model_name='hypervisorhost',
            name='hdd_capacity_GB',
        ),
        migrations.RemoveField(
            model_name='hypervisorhost',
            name='memory_capacity_GB',
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='cpu_core_num',
            field=models.PositiveIntegerField(default=2, help_text='[Core]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='cpu_socket_num',
            field=models.PositiveIntegerField(default=2, help_text='use this field for License Evaluation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='hdd_capacity',
            field=models.PositiveIntegerField(default=800, help_text='[GB]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='memory_capacity',
            field=models.PositiveIntegerField(default=64, help_text='[GB]'),
            preserve_default=False,
        ),
    ]
