# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0007_auto_20160121_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypervisorhost',
            name='physicalserver_name',
        ),
        migrations.RemoveField(
            model_name='physicalserver',
            name='name',
        ),
        migrations.AddField(
            model_name='hypervisorhost',
            name='PhysicalServer_serial',
            field=models.OneToOneField(default='MANS016516', on_delete=django.db.models.deletion.PROTECT, to='ServerAdmin.PhysicalServer'),
            preserve_default=False,
        ),
    ]
