# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0008_auto_20160121_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='note',
        ),
    ]
