# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0009_remove_virtualmachine_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmattachedvirtualhdd',
            old_name='capacity_GB',
            new_name='capacity',
        ),
    ]
