# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0010_auto_20160121_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalServerProduct',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='physicalserver',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServerAdmin.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='physicalServerProduct_name',
            field=models.ForeignKey(default='RX200S8', on_delete=django.db.models.deletion.PROTECT, to='ServerAdmin.PhysicalServerProduct'),
            preserve_default=False,
        ),
    ]
