# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0011_auto_20160122_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='memory_GB',
            new_name='memory',
        ),
    ]
