# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0012_auto_20160215_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalserver',
            old_name='physicalServerProduct_name',
            new_name='product_name',
        ),
    ]
