# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0013_auto_20160229_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypervisorhost',
            name='cpu_core_num_for_vm',
            field=models.PositiveIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hypervisorhost',
            name='hdd_capacity_for_vm',
            field=models.PositiveIntegerField(default=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hypervisorhost',
            name='memory_capacity_for_vm',
            field=models.PositiveIntegerField(default=224),
            preserve_default=False,
        ),
    ]
