# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0014_auto_20160304_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisorhost',
            name='cpu_core_num_for_vm',
            field=models.PositiveIntegerField(help_text='[Core]'),
        ),
        migrations.AlterField(
            model_name='hypervisorhost',
            name='hdd_capacity_for_vm',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
        migrations.AlterField(
            model_name='hypervisorhost',
            name='memory_capacity_for_vm',
            field=models.PositiveIntegerField(help_text='[GB]'),
        ),
    ]
