# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAdmin', '0016_auto_20160325_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='console_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rack',
            name='serial',
            field=models.CharField(max_length=128),
        ),
    ]
